#!/bin/sh

# raspi-hacks.SlackBuild
# Modifications for Slackware ARM on Raspberry Pi -- see README file for details
#
# Copyright 2012 David Spencer, Baildon, West Yorkshire, U.K.
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM="raspi-hacks"
VERSION=${VERSION:-1.0}
ARCH="arm"
BUILD=${BUILD:-1}
TAG=${TAG:-}

CWD=$(pwd)
TMP=${TMP:-/tmp}
OUTPUT=${OUTPUT:-/tmp}
PKG=$TMP/package-$PRGNAM

rm -rf $PKG
mkdir -p $TMP $PKG

mkdir -p $PKG/install

cat << EOF >> $PKG/install/doinst.sh
# /etc/inittab -- modify serial port entry 's0'
sed -i \
  -e 's;^s0:12345:respawn:/sbin/agetty 115200 ttyS0 vt100\$;#s0:12345:respawn:/sbin/agetty -L ttyAMA0 9600 vt100;' \
  etc/inittab
EOF

cat << EOF >> $PKG/install/doinst.sh
# /etc/rc.d/rc.local -- set time from network
if ! grep -q sntp etc/rc.d/rc.local ; then
  echo '' >> etc/rc.d/rc.local
  echo "# Added by $PRGNAM-$VERSION-$ARCH-$BUILD$TAG" >> etc/rc.d/rc.local
  echo 'sntp -s pool.ntp.org >/dev/null &' >> etc/rc.d/rc.local
fi
EOF

mkdir -p $PKG/sbin
cp -a $CWD/fakeclock.sh $PKG/sbin
chmod 755 $PKG/sbin/fakeclock.sh
( cd $PKG/sbin; ln -s fakeclock.sh hwclock )
cat << EOF >> $PKG/install/doinst.sh
# /sbin/hwclock -- save the original (from util-linux)
if [ -f sbin/hwclock -a ! -L sbin/hwclock ]; then
  mv sbin/hwclock sbin/hwclock.orig
fi
EOF

mkdir -p $PKG/etc
echo "vm.min_free_kbytes = 32768" > $PKG/etc/sysctl.conf.new
cat << EOF >> $PKG/install/doinst.sh
# /etc/sysctl.conf -- set vm.min_free_kbytes
config() {
  NEW="\$1"
  OLD="\$(dirname \$NEW)/\$(basename \$NEW .new)"
  # If there's no config file by that name, mv it over:
  if [ ! -r \$OLD ]; then
    mv \$NEW \$OLD
  elif [ "\$(cat \$OLD | md5sum)" = "\$(cat \$NEW | md5sum)" ]; then # toss the redundant copy
    rm \$NEW
  fi
  # Otherwise, we leave the .new copy for the admin to consider...
}
config etc/sysctl.conf.new
EOF

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
  $CWD/README \
  $PKG/usr/doc/$PRGNAM-$VERSION

cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
