#!/bin/sh

# Device nodes for Raspberry Pi
# David Spencer <baildon.research@googlemail.com> 8 July 2012
# The most appropriate documentation for this package is a script :-)

mknod -m 660 mmcblk0    b 179  0
mknod -m 660 mmcblk0p1  b 179  1
mknod -m 660 mmcblk0p2  b 179  2
mknod -m 660 mmcblk0p3  b 179  3
mknod -m 660 mmcblk0p4  b 179  4
mknod -m 660 mmcblk0p5  b 179  5
mknod -m 660 mmcblk0p6  b 179  6
mknod -m 660 mmcblk0p7  b 179  7
chown root:disk mmcblk*

mknod -m 600 usbdev1.1  c 189  0
mknod -m 600 usbdev1.2  c 189  1
mknod -m 600 usbdev1.3  c 189  2
chown root:root usbdev*

mknod -m 660 ttyAMA0    c 204 64
chown root:dialout ttyAMA*
